development: &default
  adapter: postgresql
  database: rails-dev-template_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: rails-dev-template_test

production:
  <<: *default
  database: rails_dev_template_production
  username: rails_dev_template_production
  password: test